// The web app inherits the root flat config; next-env.d.ts is generated by
// Next and uses triple-slash references we do not control.
import root from "../../eslint.config.mjs";

export default [...root, { ignores: ["next-env.d.ts", ".next/**"] }];
