ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM maman_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM maman_app;
REVOKE USAGE ON SCHEMA public FROM maman_app;
DROP ROLE IF EXISTS maman_app;
