// GENERATED by scripts/build-packs.ts (pnpm packs:generate) — do not edit.
// The webview's copy of domain/packs/*.json; the Rust core reads the JSON
// from disk. packs:check fails CI when either drifts from the YAML source.
import type { DomainPack } from "./schema.js";

export const SHIPPED_PACKS: DomainPack[] = [
  {
    "domain": "finops",
    "version": "0.1.0",
    "objects": [
      {
        "id": "invoice",
        "aliases": [
          "bill",
          "vendor_invoice",
          "ap_invoice"
        ],
        "detection_hints": {
          "app_categories": [
            "ap_automation",
            "erp",
            "email",
            "pdf_viewer"
          ],
          "label_patterns": [
            "invoice",
            "INV-",
            "bill #",
            "amount due"
          ],
          "target_roles": []
        }
      },
      {
        "id": "purchase_order",
        "aliases": [
          "po"
        ],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [
            "PO-",
            "purchase order"
          ],
          "target_roles": []
        }
      },
      {
        "id": "receipt",
        "aliases": [
          "goods_receipt",
          "grn"
        ],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [],
          "target_roles": []
        }
      },
      {
        "id": "gl_entry",
        "aliases": [
          "journal_entry",
          "journal",
          "je"
        ],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [
            "GL",
            "journal",
            "debit",
            "credit",
            "account code"
          ],
          "target_roles": []
        }
      },
      {
        "id": "accrual",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [],
          "target_roles": []
        }
      },
      {
        "id": "vendor",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [
            "vendor",
            "supplier",
            "payee"
          ],
          "target_roles": []
        }
      },
      {
        "id": "payment_run",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [
            "payment batch",
            "pay run",
            "ACH",
            "wire"
          ],
          "target_roles": []
        }
      },
      {
        "id": "expense_report",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [],
          "target_roles": []
        }
      },
      {
        "id": "close_task",
        "aliases": [
          "close_checklist_item"
        ],
        "detection_hints": {
          "app_categories": [
            "close_management"
          ],
          "label_patterns": [
            "close",
            "flux",
            "reconciliation"
          ],
          "target_roles": []
        }
      },
      {
        "id": "cost_anomaly",
        "aliases": [],
        "detection_hints": {
          "app_categories": [
            "cloud_cost",
            "spend_management"
          ],
          "label_patterns": [
            "anomaly",
            "spike",
            "budget alert"
          ],
          "target_roles": []
        }
      },
      {
        "id": "budget_line",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [],
          "target_roles": []
        }
      }
    ],
    "actions": [
      {
        "id": "open",
        "risk": "none",
        "on": []
      },
      {
        "id": "extract_field",
        "risk": "none",
        "on": []
      },
      {
        "id": "code_invoice",
        "risk": "medium",
        "on": [
          "invoice",
          "gl_entry"
        ]
      },
      {
        "id": "three_way_match",
        "risk": "medium",
        "on": [
          "invoice",
          "purchase_order",
          "receipt"
        ]
      },
      {
        "id": "approve_invoice",
        "risk": "high",
        "on": [
          "invoice"
        ]
      },
      {
        "id": "reconcile",
        "risk": "medium",
        "on": [
          "gl_entry",
          "close_task"
        ]
      },
      {
        "id": "post_journal",
        "risk": "high",
        "on": [
          "gl_entry",
          "accrual"
        ]
      },
      {
        "id": "schedule_payment",
        "risk": "critical",
        "on": [
          "payment_run",
          "invoice"
        ]
      },
      {
        "id": "release_payment",
        "risk": "critical",
        "on": [
          "payment_run"
        ]
      },
      {
        "id": "flag_exception",
        "risk": "low",
        "on": []
      },
      {
        "id": "draft_email",
        "risk": "low",
        "on": []
      },
      {
        "id": "send_email",
        "risk": "high",
        "on": []
      },
      {
        "id": "update_budget",
        "risk": "medium",
        "on": [
          "budget_line"
        ]
      }
    ],
    "workflows": [
      {
        "id": "invoice_intake",
        "name": "Invoice intake & coding",
        "cadence": "continuous",
        "signature": [
          [
            "open",
            "invoice",
            "*"
          ],
          [
            "extract_field",
            "invoice",
            "*"
          ],
          [
            "code_invoice",
            "gl_entry",
            "*"
          ],
          [
            "flag_exception|submit",
            "invoice",
            "*"
          ]
        ],
        "min_reps_with_template": 2,
        "trigger": {
          "opening_ngram": 2
        },
        "default_autonomy_ceiling": "stage_only"
      },
      {
        "id": "three_way_match",
        "name": "PO / invoice / receipt match",
        "cadence": "continuous",
        "signature": [
          [
            "open",
            "invoice",
            "*"
          ],
          [
            "open",
            "purchase_order",
            "*"
          ],
          [
            "three_way_match",
            "invoice",
            "*"
          ],
          [
            "approve_invoice|flag_exception",
            "invoice",
            "*"
          ]
        ],
        "min_reps_with_template": 2
      },
      {
        "id": "month_end_accruals",
        "name": "Month-end accrual journals",
        "cadence": "fiscal_monthly",
        "signature": [
          [
            "open",
            "close_task",
            "*"
          ],
          [
            "extract_field",
            "accrual",
            "*"
          ],
          [
            "post_journal",
            "accrual",
            "*"
          ]
        ],
        "min_reps_with_template": 2,
        "pre_stage": {
          "days_before_close": 3,
          "mode": "draft_only"
        }
      },
      {
        "id": "bank_reconciliation",
        "name": "Bank / GL reconciliation",
        "cadence": "fiscal_monthly",
        "signature": [
          [
            "open",
            "gl_entry",
            "*"
          ],
          [
            "reconcile",
            "gl_entry",
            "*"
          ],
          [
            "flag_exception|post_journal",
            "gl_entry",
            "*"
          ]
        ],
        "min_reps_with_template": 2
      },
      {
        "id": "spend_anomaly_triage",
        "name": "Cost anomaly triage",
        "cadence": "event_driven",
        "signature": [
          [
            "open",
            "cost_anomaly",
            "*"
          ],
          [
            "extract_field",
            "cost_anomaly",
            "*"
          ],
          [
            "flag_exception|draft_email",
            "*",
            "*"
          ]
        ],
        "min_reps_with_template": 3
      },
      {
        "id": "expense_review",
        "name": "Expense report review",
        "cadence": "weekly",
        "signature": [
          [
            "open",
            "expense_report",
            "*"
          ],
          [
            "extract_field",
            "expense_report",
            "*"
          ],
          [
            "approve_invoice|flag_exception",
            "expense_report",
            "*"
          ]
        ],
        "min_reps_with_template": 3
      }
    ],
    "policy": {
      "segregation_of_duties": [
        {
          "cannot_combine": [
            "code_invoice",
            "approve_invoice"
          ]
        },
        {
          "cannot_combine": [
            "post_journal",
            "reconcile"
          ]
        },
        {
          "cannot_combine": [
            "schedule_payment",
            "release_payment"
          ]
        }
      ],
      "autonomy_rules": [
        {
          "match": {
            "action": "schedule_payment"
          },
          "rule": {
            "max_level": "draft_only",
            "dual_control": true
          }
        },
        {
          "match": {
            "action": "release_payment"
          },
          "rule": {
            "max_level": "never_autonomous",
            "dual_control": true
          }
        },
        {
          "match": {
            "action": "approve_invoice",
            "amount_usd_gt": 5000
          },
          "rule": {
            "always_gate": true
          }
        },
        {
          "match": {
            "action": "post_journal"
          },
          "rule": {
            "max_level": "stage_only"
          }
        },
        {
          "match": {
            "action": "send_email"
          },
          "rule": {
            "max_level": "draft_only"
          }
        }
      ],
      "receipts": {
        "immutable": true,
        "retain_days": 2555
      },
      "amount_extraction_required_for": [
        "approve_invoice",
        "schedule_payment"
      ]
    },
    "proactivity": {
      "calendar": "fiscal",
      "quiet_periods": [],
      "event_triggers": [],
      "suggestion_timing": {
        "fiscal_monthly_workflows": {
          "surface": "pre_close",
          "days_before": 3,
          "copy": "Close starts {date}. I can pre-stage {workflow} — last cycle matched {runs_matched}/{runs_tested}."
        },
        "continuous_workflows": {
          "surface": "after_verification"
        },
        "event_driven_workflows": {
          "surface": "on_trigger"
        }
      },
      "dismissal_learning": {
        "source": "suggestion_history",
        "never_means": "suppress_workflow_family",
        "not_now_backoff_days": [
          14,
          45,
          120
        ]
      }
    }
  },
  {
    "domain": "revops",
    "version": "0.1.0",
    "objects": [
      {
        "id": "lead",
        "aliases": [],
        "detection_hints": {
          "app_categories": [
            "crm",
            "marketing_automation",
            "email"
          ],
          "label_patterns": [
            "lead",
            "MQL",
            "inbound"
          ],
          "target_roles": []
        }
      },
      {
        "id": "contact",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [],
          "target_roles": []
        }
      },
      {
        "id": "account",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [
            "account",
            "company"
          ],
          "target_roles": []
        }
      },
      {
        "id": "opportunity",
        "aliases": [
          "deal",
          "opp"
        ],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [
            "opportunity",
            "deal",
            "stage",
            "close date"
          ],
          "target_roles": []
        }
      },
      {
        "id": "quote",
        "aliases": [
          "proposal"
        ],
        "detection_hints": {
          "app_categories": [
            "cpq",
            "esign"
          ],
          "label_patterns": [
            "quote",
            "proposal",
            "pricing"
          ],
          "target_roles": []
        }
      },
      {
        "id": "contract",
        "aliases": [],
        "detection_hints": {
          "app_categories": [
            "esign",
            "clm"
          ],
          "label_patterns": [
            "contract",
            "order form",
            "MSA",
            "signature"
          ],
          "target_roles": []
        }
      },
      {
        "id": "renewal",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [
            "renewal",
            "expires",
            "term end"
          ],
          "target_roles": []
        }
      },
      {
        "id": "pipeline_report",
        "aliases": [],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [],
          "target_roles": []
        }
      },
      {
        "id": "commission_line",
        "aliases": [],
        "detection_hints": {
          "app_categories": [
            "commissions",
            "spreadsheet"
          ],
          "label_patterns": [
            "commission",
            "payout",
            "attainment"
          ],
          "target_roles": []
        }
      },
      {
        "id": "activity_log",
        "aliases": [
          "call_note",
          "meeting_note"
        ],
        "detection_hints": {
          "app_categories": [],
          "label_patterns": [],
          "target_roles": []
        }
      }
    ],
    "actions": [
      {
        "id": "open",
        "risk": "none",
        "on": []
      },
      {
        "id": "extract_field",
        "risk": "none",
        "on": []
      },
      {
        "id": "enrich",
        "risk": "low",
        "on": [
          "lead",
          "account",
          "contact"
        ]
      },
      {
        "id": "route_lead",
        "risk": "medium",
        "on": [
          "lead"
        ]
      },
      {
        "id": "update_crm_field",
        "risk": "medium",
        "on": [
          "lead",
          "opportunity",
          "account",
          "contact"
        ]
      },
      {
        "id": "advance_stage",
        "risk": "medium",
        "on": [
          "opportunity"
        ]
      },
      {
        "id": "generate_quote",
        "risk": "medium",
        "on": [
          "quote",
          "opportunity"
        ]
      },
      {
        "id": "apply_discount",
        "risk": "high",
        "on": [
          "quote"
        ]
      },
      {
        "id": "send_for_signature",
        "risk": "critical",
        "on": [
          "contract",
          "quote"
        ]
      },
      {
        "id": "draft_email",
        "risk": "low",
        "on": []
      },
      {
        "id": "send_email",
        "risk": "high",
        "on": []
      },
      {
        "id": "log_activity",
        "risk": "low",
        "on": [
          "activity_log"
        ]
      },
      {
        "id": "bulk_update",
        "risk": "high",
        "on": [
          "*"
        ]
      },
      {
        "id": "reconcile_commissions",
        "risk": "medium",
        "on": [
          "commission_line"
        ]
      }
    ],
    "workflows": [
      {
        "id": "lead_routing",
        "name": "Inbound lead triage & routing",
        "cadence": "event_driven",
        "signature": [
          [
            "open",
            "lead",
            "*"
          ],
          [
            "enrich",
            "lead",
            "*"
          ],
          [
            "update_crm_field",
            "lead",
            "owner_field"
          ],
          [
            "route_lead|draft_email",
            "lead",
            "*"
          ]
        ],
        "min_reps_with_template": 2,
        "trigger": {
          "opening_ngram": 2
        },
        "default_autonomy_ceiling": "stage_only"
      },
      {
        "id": "quote_to_cash",
        "name": "Quote generation from opportunity",
        "cadence": "continuous",
        "signature": [
          [
            "open",
            "opportunity",
            "*"
          ],
          [
            "extract_field",
            "opportunity",
            "*"
          ],
          [
            "generate_quote",
            "quote",
            "*"
          ],
          [
            "draft_email|send_for_signature",
            "quote",
            "*"
          ]
        ],
        "min_reps_with_template": 2
      },
      {
        "id": "renewal_motion",
        "name": "Renewal prep & outreach",
        "cadence": "date_driven",
        "signature": [
          [
            "open",
            "renewal",
            "*"
          ],
          [
            "extract_field",
            "renewal",
            "*"
          ],
          [
            "generate_quote|draft_email",
            "*",
            "*"
          ]
        ],
        "min_reps_with_template": 2,
        "pre_stage": {
          "days_before_renewal": 30,
          "mode": "draft_only"
        }
      },
      {
        "id": "pipeline_hygiene",
        "name": "Pipeline hygiene sweep",
        "cadence": "weekly",
        "signature": [
          [
            "open",
            "pipeline_report",
            "*"
          ],
          [
            "open",
            "opportunity",
            "*"
          ],
          [
            "update_crm_field",
            "opportunity",
            "close_date|stage|next_step"
          ]
        ],
        "min_reps_with_template": 3,
        "notes": "bulk_update policy applies when >10 records in one episode"
      },
      {
        "id": "meeting_logging",
        "name": "Post-meeting CRM logging",
        "cadence": "event_driven",
        "signature": [
          [
            "open",
            "activity_log",
            "*"
          ],
          [
            "extract_field",
            "activity_log",
            "*"
          ],
          [
            "log_activity",
            "activity_log",
            "*"
          ],
          [
            "update_crm_field",
            "opportunity",
            "next_step"
          ]
        ],
        "min_reps_with_template": 2
      },
      {
        "id": "commission_reconciliation",
        "name": "Commission statement reconciliation",
        "cadence": "fiscal_monthly",
        "signature": [
          [
            "open",
            "commission_line",
            "*"
          ],
          [
            "reconcile_commissions",
            "commission_line",
            "*"
          ],
          [
            "flag_exception|draft_email",
            "*",
            "*"
          ]
        ],
        "min_reps_with_template": 2
      }
    ],
    "policy": {
      "segregation_of_duties": [
        {
          "cannot_combine": [
            "apply_discount",
            "send_for_signature"
          ]
        },
        {
          "cannot_combine": [
            "reconcile_commissions",
            "update_crm_field"
          ]
        }
      ],
      "autonomy_rules": [
        {
          "match": {
            "action": "send_email"
          },
          "rule": {
            "max_level": "draft_only"
          }
        },
        {
          "match": {
            "action": "send_for_signature"
          },
          "rule": {
            "max_level": "never_autonomous",
            "dual_control": true
          }
        },
        {
          "match": {
            "action": "apply_discount",
            "discount_pct_gt": 10
          },
          "rule": {
            "always_gate": true
          }
        },
        {
          "match": {
            "action": "bulk_update",
            "record_count_gt": 10
          },
          "rule": {
            "max_level": "dry_run_first",
            "always_gate": true
          }
        },
        {
          "match": {
            "action": "advance_stage"
          },
          "rule": {
            "max_level": "stage_only"
          }
        }
      ],
      "receipts": {
        "immutable": true,
        "retain_days": 1095
      },
      "amount_extraction_required_for": [],
      "crm_write_safety": {
        "snapshot_before_write": true,
        "revert_command": true
      }
    },
    "proactivity": {
      "calendar": "none",
      "quiet_periods": [],
      "event_triggers": [
        {
          "watch": "renewal",
          "field": "term_end",
          "lead_days": 30,
          "copy": "{account}'s renewal is {days} out. I can draft the renewal packet — matched {runs_matched}/{runs_tested} on past renewals."
        },
        {
          "watch": "lead",
          "condition": "new_unrouted",
          "surface": "on_trigger"
        }
      ],
      "suggestion_timing": {
        "weekly_workflows": {
          "surface": "same_weekday_observed"
        },
        "continuous_workflows": {
          "surface": "after_verification"
        }
      },
      "dismissal_learning": {
        "source": "suggestion_history",
        "never_means": "suppress_workflow_family",
        "not_now_backoff_days": [
          14,
          45,
          120
        ]
      }
    }
  }
];
